"""Tests for the generator module and feed outputs."""

import os
import tempfile
import xml.etree.ElementTree as ET
from unittest.mock import MagicMock, patch

from rtp_podcaster.extractor import Episode
from rtp_podcaster.generator import RSSGenerator


def test_generator_creation():
    """Test successful initialization and URL generation."""
    gen = RSSGenerator(program_id=254)
    assert gen.program_id == 254
    assert gen.show_url == "https://www.rtp.pt/play/p254/alta-tensao"
    assert gen.SHOW_NAME == "Alta Tensão"


def test_generator_feed_lifecycle():
    """Test full creation, merging, and GUID tracking lifecycle."""
    gen = RSSGenerator(program_id=254)

    episodes = [
        Episode(
            url="http://test.com/ep1",
            title="Test Episode 1",
            date_str="8 Abr. 2026",
            guid="unique-guid-1",
            mp3_url="http://test.com/ep1.mp3",
        )
    ]

    with tempfile.TemporaryDirectory() as tmpdir:
        test_file = os.path.join(tmpdir, "test_feed.xml")

        # Guarantee no existing guids on blank load
        assert len(gen.get_existing_guids(test_file)) == 0

        # Create feed manually simulating 1st run
        gen.create_or_update_feed(episodes, test_file, max_episodes=5)
        assert os.path.exists(test_file)

        # Validate standard feedparser parse load back into internal cache natively
        guids = gen.get_existing_guids(test_file)
        assert "unique-guid-1" in guids

        # Inject secondary mock simulation imitating week 2
        episodes_2 = [
            Episode(
                url="http://test.com/ep2",
                title="Test Episode 2",
                date_str="9 Abr. 2026",
                guid="unique-guid-2",
                mp3_url="http://test.com/ep2.mp3",
            )
        ]
        # Append target natively utilizing existing structure
        gen.create_or_update_feed(episodes_2, test_file, max_episodes=5)

        guids_updated = gen.get_existing_guids(test_file)
        assert "unique-guid-1" in guids_updated
        assert "unique-guid-2" in guids_updated

        # Secure XML structural assertions manually outside of package mapping logic
        tree = ET.parse(test_file)
        root = tree.getroot()
        items = root.findall(".//item")
        assert len(items) == 2

        titles = [item.find("title").text for item in items]
        assert "Test Episode 2" in titles
        assert "Test Episode 1" in titles


def test_generator_exceptions_safely_ignored():
    """Test exceptions generated by feedparser failing gracefully safely."""
    gen = RSSGenerator(program_id=254)
    episodes = [
        Episode(
            url="http://test.com/ep1",
            title="Test",
            date_str="8 Abr.",
            guid="test-guid",
            mp3_url="http://test.mp3",
        )
    ]

    with tempfile.TemporaryDirectory() as tmpdir:
        test_file = os.path.join(tmpdir, "test_feed.xml")
        with open(test_file, "w") as f:
            f.write("Broken XML Simulation File")

        with patch("feedparser.parse") as mock_parse:
            mock_parse.side_effect = Exception("Simulated Parser Failure")

            # Line 35 exception trap
            guids = gen.get_existing_guids(test_file)
            assert len(guids) == 0

            # Line 74 exception trap
            gen.create_or_update_feed(episodes, test_file, max_episodes=5)


class MockEntry(dict):
    def __getattr__(self, item):
        try:
            return self[item]
        except KeyError:
            raise AttributeError(item)


def test_generator_edge_cases():
    """Verify fallback mechanisms for missing metadata mappings."""
    gen = RSSGenerator(program_id=254)

    with tempfile.TemporaryDirectory() as tmpdir:
        test_file = os.path.join(tmpdir, "test_feed.xml")

        with patch("feedparser.parse") as mock_parse:
            # Simulate historical entry missing "id" but containing "guid",
            # and another missing "enclosures" and having broken "published" tracking
            mock_feed = MagicMock()

            entry1 = MockEntry(
                {"guid": "legacy-guid", "title": "A"}
            )  # Line 33 `elif "guid" in entry` coverage
            entry2 = MockEntry(
                {
                    "id": "broken-pub",
                    "title": "B",
                    "published": "Bad Date String",
                    "enclosures": [MockEntry({"href": "http://test.mp3"})],
                }
            )  # Line 100/114 coverage

            mock_feed.entries = [entry1, entry2]
            mock_parse.return_value = mock_feed

            # create file to trigger history fetch
            with open(test_file, "w") as f:
                f.write("<xml></xml>")

            # Line 33 Test check
            guids = gen.get_existing_guids(test_file)
            assert "legacy-guid" in guids
            assert "broken-pub" in guids

            # Line 100 (continue lacking enclosure) & Line 114 (bad pubdate passed)
            gen.create_or_update_feed([], test_file)


def test_generator_image_url():
    """Verify that a provided image URL is written into the generated RSS feed."""
    gen = RSSGenerator(program_id=254)
    episodes = [
        Episode(
            url="http://test.com/ep1",
            title="Test Episode",
            date_str="8 Abr. 2026",
            guid="guid-img-test",
            mp3_url="http://test.com/ep1.mp3",
        )
    ]

    with tempfile.TemporaryDirectory() as tmpdir:
        test_file = os.path.join(tmpdir, "test_feed.xml")
        gen.create_or_update_feed(
            episodes,
            test_file,
            image_url="https://cdn-images.rtp.pt/EPG/radio/imagens/1068_12880_9537.jpg",
        )

        tree = ET.parse(test_file)
        root = tree.getroot()
        channel = root.find("channel")
        assert channel is not None

        # Verify channel-level <image>
        image = channel.find("image")
        assert image is not None
        url_el = image.find("url")
        assert url_el is not None
        assert url_el.text == "https://cdn-images.rtp.pt/EPG/radio/imagens/1068_12880_9537.jpg"

        # Verify per-episode <itunes:image>
        ns = {"itunes": "http://www.itunes.com/dtds/podcast-1.0.dtd"}
        item = root.find(".//item")
        assert item is not None
        itunes_image = item.find("itunes:image", ns)
        assert itunes_image is not None
        assert (
            itunes_image.get("href")
            == "https://cdn-images.rtp.pt/EPG/radio/imagens/1068_12880_9537.jpg"
        )
